# SITE CONFIGURATION
baseurl: ""
url: "jcbucio.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Juan Carlos Bucio T.                                    # site's title
description: "Blog y portafolio personal"      # used by search engines
avatar: assets/img/authors/profile-pic.png     # Empty for no avatar in navbar
favicon: assets/pick.png                         # Icon displayed in the tab

# Header and footer text
header_text: Ciencia de datos | Geociencias | Geofísica  # Change Blog header text
header_feature_image: assets/img/feature-img/earth.jpg
footer_text: >
  <i>Juan Carlos Bucio T.<br>Powered by <a href="https://jekyllrb.com/" target="_blank" rel="noopener noreferrer">Jekyll</a> and <a href="https://github.com/sylhare/Type-on-Strap" target="_blank" rel="noopener noreferrer">Type-on-Strap</a></i>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/color/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments
cusdis_app_id: d771351c-606b-4417-b040-a12d906bd517     # Your cusdis data-app-id
color_theme: dark                                       # auto, dark or light

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-figure]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
